server:
  port: 8763
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: sunbufu-hello-web

security:
  user:
    name: sunbufu
    password: 123456